<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE GOMiner [
        <!ELEMENT GOMiner (term)*>
        <!ELEMENT term (goid|term)*>
        <!ATTLIST term
                cuid CDATA #REQUIRED>
        <!ELEMENT goid (#PCDATA)>
        ]>
<GOMiner>
    <term cuid="t1234">
        <goid>0005275</goid>
        <term cuid="t1234">
            <goid>0005276</goid>
        </term>
        <term cuid="t1234">
            <goid>0005277</goid>
        </term>
        <term cuid="t1234">
            <goid>0005329</goid>
        </term>
  </term>
</GOMiner>
