=== JetBrains/intellij-community/platform/build-scripts/src/org/jetbrains/intellij/build/product-info.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://jetbrains.org/intellij/schema/product.schema.json",
  "title": "IntelliJ-based IDE installation",
  "description": "Meta-information about installation of an IDE based on IntelliJ Platform",
  "version": "0.2",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "name", "version", "buildNumber", "productCode", "launch"
  ],
  "properties": {
    "name": {
      "description": "Full name of the product without edition, e.g. 'IntelliJ IDEA' or 'PyCharm'",
      "type": "string"
    },
    "version": {
      "description": "Marketing version of the product, e.g. '2018.3'",
      "type": "string"
    },
    "versionSuffix": {
      "description": "Specifies type of this product version which is shown after the version number in the UI, e.g. 'EAP', 'EAP 2', 'Preview', etc. May be omitted (e.g. for release builds).",
      "type": "string"
    },
    "buildNumber": {
      "description": "Build number of the product, e.g. '183.239' or '183.SNAPSHOT'",
      "type": "string"
    },
    "productCode": {
      "description": "Product code (e.g. 'IC' for IntelliJ IDEA Community Edition) as used in full build number",
      "type": "string"
    },
    "dataDirectoryName": {
      "description": "Name of a directory used for storing settings, caches, etc. (e.g. 'IntelliJIdea2020.1' for IntelliJ IDEA 2020.1); the full path to the directory is OS-specific.",
      "type": "string"
    },
    "svgIconPath": {
      "description": "Path to an SVG file which contains the product icon (relative to the parent directory of this file, '/' as a separator, may start with '../'), e.g. 'bin/idea.svg'",
      "type": "string"
    },
    "productVendor": {
      "description": "Short company name as used in config paths, e.g. ~/.config/JetBrains/...",
      "type": "string"
    },
    "launch": {
      "description": "Specifies how the IDE can be launched",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["os", "launcherPath", "vmOptionsFilePath"],
        "additionalProperties": false,
        "minItems": 1,
        "properties": {
          "os": {
            "description": "Operation system this launch method is supposed to be used for",
            "type": "string",
            "enum": ["Windows", "Linux", "macOS"]
          },
          "arch": {
            "description": "CPU Architecture this launch method is supposed to be used for",
            "type": "string",
            "enum": ["amd64", "aarch64"]
          },
          "launcherPath": {
            "description": "Path to an executable file which starts the IDE (relative to the parent directory of this file, '/' as a separator, may start with '../'), e.g. 'bin/idea.sh'",
            "type": "string"
          },
          "javaExecutablePath": {
            "description": "Path to an JRE executable file (relative to the parent directory of this file, '/' as a separator, may start with '../'), e.g. 'jre64/bin/java'. May be missing if JRE isn't bundled with the product.",
            "type": "string"
          },
          "vmOptionsFilePath": {
            "description": "Path to a file containing JVM options which are used to start the IDE (relative to the parent directory of this file, '/' as a separator, may start with '../'), e.g. 'bin/idea64.vmoptions'",
            "type": "string"
          },
          "startupWmClass": {
            "description": "Value of 'WMClass' property used by some Linux desktop distributions to associate windows with the owning application, e.g. 'jetbrains-idea'. May be specified only if 'os' is 'Linux'.",
            "type": "string"
          },
          "bootClassPathJarNames" : {
            "description": "Names of JARs inside `IDE_HOME/lib` directory which need to be added to the JVM classpath to start the IDE",
            "type": "array",
            "items": {
              "type": "string",
              "minItems": 1
            }
          },
          "additionalJvmArguments" : {
            "description": "Additional arguments required for IDE to launch which are not supposed to be changed by a user, e.g. various --add-opens",
            "type" : "array",
            "items": {
              "type": "string",
              "minItems": 1
            }
          }
        }
      }
    },
    "customProperties": {
      "description": "Array of arbitrary key-value pairs",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["key", "value"],
        "additionalProperties": false,
        "minItems": 0,
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        }
      }
    },
    "bundledPlugins": {
      "description": "IDs of plugins bundled into this distribution, e.g. 'JUnit' or 'com.intellij.java'",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "fileExtensions": {
      "description": "Patterns of file names supported by this IDE and its bundled plugins, e.g. '*.java', '*.html' or 'Dockerfile'",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "modules": {
      "description": "IDs of product modules (non-removable bundled plugins) contained in this distribution, e.g. 'com.intellij.modules.lang'; see https://plugins.jetbrains.com/docs/intellij/plugin-compatibility.html#modules",
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== JetBrains/intellij-community/platform/platform-tests/testData/productInfo/idea-2020.1.4-Linux/product-info.json
{
  "name": "IntelliJ IDEA",
  "version": "2020.1.4",
  "buildNumber": "201.8743.12",
  "productCode": "IU",
  "dataDirectoryName": "IntelliJIdea2020.1",
  "svgIconPath": "bin/idea.svg",
  "launch": [
    {
      "os": "Linux",
      "launcherPath": "bin/idea.sh",
      "javaExecutablePath": "jbr/bin/java",
      "vmOptionsFilePath": "bin/idea64.vmoptions",
      "startupWmClass": "jetbrains-idea"
    }
  ]
}
